### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by leloufadel** [Eccb7/react-todo-app#2]
You are doing an excellent job by implementing functionalities like adding, editing, and deleting to-do lists. However, there are a few areas that could use some improvement. Specifically, the Readme file should have a more professional tone and provide a clear description of your app's purpose and features. Keep up the good work, and I encourage you to refine the Readme to make it more informative about your app, and deploy your app. 

Happy coding 😄

**Comment by Eccb7** [comment]
Thanks for the review. I'll take into consideration the changes.
